language: node_js
sudo: false
node_js:
- 4
- 6
- 8
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh

deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: I7MhEd++LqQyxQcivH7thVwazRHmV1By4TzjdKicHHur4qHaQzjiq5a5pM7LtPzrDbgxZapBwA/9okz13iSGeqG+/Nks8Nc2ac1wGOpnewnOSNnCw4e8tJT7Ug88s5cdcIfKeA0GhzUrRie5xEADBk1+9T+UXUujGiUNYcVftmqwV2xEHeE2FqjLGat0OLLx33llpM7ppt3pC00W7dRz/1IEY1Ov/U4lSqEqlppGfbLhi3X7SrgK66eqAiBS21lHUc2EF+/9Z5cebYjVMB6Wlbb6DcbYsm2rUEXiNmKu23P89yOBgLx9VEImDnyfOAfwGXX0H8fHgDXXC0dQboC9pCcBMbe6v4PH9zg0qs2pfUbsBTEX8m376dI1jm8RZhwVAQ0o1wsqLe0d11+p9hEROp0vs4Vgi7Uern7Fzyvpsi/b/ZpxIxbldqbhyb9GVgcrepfBvG3OFCVxNTcjYjyUjn1BATHZA9MdFQgsZTf//AjsbuQp6KGEPzCUTRLlzc5TvJ6LwsPw5Kvbj5hTLUblcgbPNTQH31vcHxkqWaQ8cnwSFinjiKJtdYn5SCHHpMLxdGSg2Pr16mNP+uByf6/A7tpb304TOJGzv3WQdZrwaOTG0KFRIGb4Lurjn+sZXzIsKkboUsJDijdnuxOLCl5a7aPT0JfP+I2IR0GHcAdpG0M=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: o3fw+zSFJMnmM1c2kJJ4zXlPTYO6Zhr4jeQpXKYDhwatO7PC15IyRv7lfCRvVgrPAZqxE2RRc7+0xd/FEpkO8SI+1U6WD/ZD4MIa7TlcrnTqN3hyLL0Pxu1koZVk9rTohCAcnp1tQek5xUIKO5H7VfhHRA5l4rPYnWyotV/oYciYnUpOd7/ZwZYkAYMDd/3uhI04q/gV0P+xQCPImUbkU/HwOE/drBdq3j1sWO6QjkwPN2F94+o1HJs9maixz2Z/miZamjT2xX4aoP8//dqRWA+2Dji4Jj7y7biVdV9iHljnPV4ycXhSs1DmnMICpS0QD/7mRshaYJPXRgIqIxwCyWtyoQhsw7KU6tGUWDp/Ys8v4NXcCgZotv62KrcgXfbxGtlteOvdB9dNKvJFeEQd2x09z4p1AQRseRkjEZ1Ua8JJMzFuaCawHLtk9Ouu5o4TONtDPjt2f/n7xukDSeDZDVjNYNuDIApUbRC+LdqIMOa7RTKnNcYSly6qW27e3HDvIHOqV0Vx3ar1x+zXpz7YUR7KpiFrj5QyCKjisT+ZoruAHlNnkM/1+SblPEJci8UR+Vu/mdI07MTVo/CwAfrCMl9V8hX2lcNuUyqGYsZM9VPbgg80d21t3HuUOr3j1pyf7fQxSPSNZsF9bG3gqun1g/KjaEgvceumz/2jqTCVb/E=
