language: node_js
sudo: false
node_js:
- 6
- 4.2
script:
- npm run ci
- chmod 777 ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
- export TEST_GROUP=desktop-regression
- "./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: kEe/1t2dhIveAEb7fBTz5PCjZwwSBQqfuxlXYAXPmOqPXX+2OyUNyki+/lyrVpmFhzKE2hGJWY5HTmhPCKRrJyqu9oH3D2yfxkm6w3pOdG3h2angHI2T9faGsvdHkGGaRVFzdn+G5g9Lbu3nbYMlR+QTP20MM1YBWTTq0HJ7BzV4e5FAyv05CoTOSbHtVq7SdAKCWn7Wz01efabQni7kAoMSOfoQLvru4yYpRB6Ype72v5R3kBW1sqciTjpEHLg/uGaUFAIsRPIva8ZZhGnG8zFLsSSeNM1FfV9obzrBMTzqlpniVXvb/sdqNZwxPwpA1foJJJ6Hj19BCA5W25vGrA8m5oucd3Vd2cEl7IdMPDRY6Dzr5O4z6YSOGUiDkQTIaiLgDKqNBYLnyh3gjLW7fu8bL36LVxJ5R7pwmvE1mXHqq0SQS9ShgBFLBNXmxEdGkBxSCglqjnDJqO8ZAbIm21ASAS1q4WElHSxF/e+S2HM0AkXcYmROWrNQLYEIS7Fw+S65QZFiEJCmh1kVWwly9yYFbiUJoN9tWGLo5wYkWtFIclCrLHBc/WD0N0nzKSL6eDluQKYGEcHmcSp07zKnrVGr6HmLad4dCuH6YteO8Z16+tIayXgfJuO90zEpC4bxT7kgbZx7LIaj64VVDsVp4J08k11LWsUMxCTJ9xIx/ho=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iaonK0LD5C8YfooAUmXf7wL72L4jxR5Z3FztZEEzDfQ2ewUAamOaM6ft3dhmj9B8yXROR4PhgfRArrVtqIv1ECsuq0PvL9o5zb56YUu6iAJiu7sYggnfYPhc5qcO+v9/5tRkjICLfeajdN8KdOIuEW4Z55ZC063JLhQCdXcFQ9aSc5CauQp/mWI7Oo9BuDLUSWh4ZkO/WvHxAadzKQTrVyIrOsQraAHZWAXhWjwdlAsV/d++qaQ9j+yWaheGagt/VQV2aqZodffyfCrQEtfr3k74WxFgQVtu3ZKG5VgeBeestV7eyBWTrXlKvnS5VhgASLR9fh0sNbUNrow/Hf8PxznRFCx/TDIXB12Y+Lb17ZbutM4eqQsTfHYhrp7lAx+t8hTcFWvMQs1HvWjuO5W35E371p9+8hSIADSAtA+SP88gVusJRVBe+Sv0VqwIPEKYii4WFbyfQd/VBtk5CooPi2wtZvOj9lSR0k7KeMBf2IGipINDKm296g+uE7KJc4WTF2nx0fdNmSLEie3MVU6YVh4HubEFOlK3CMSEgxut+D2j83Lfj9QBy51bkfZfd/jz/Z5gCFLI/9PgNkaHJFRNKMaAn7QDNFdH8DmFWSdv70ywNXO7MINNFyHPWgpdIf9Adqo9NRlL3qUa/KsRR0JwNDS4i6UVwblwGBYjEoBld48=
