language: node_js
sudo: false
node_js:
- 5.2
- 4.2
script:
- npm run ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: IlTfQBp/E1Mz+zCGacSVw6lfcEizX3PF6Y3RcNBvBHhP1uBXoU35hQssQNJVhd8/NxdYC195bVwsiUeF8jIKnv/lBMoAtpK3V8ibKz6YMfwn+V1BH3OKqgXcqs0G+wrmgQJY4rRYw/ElhMRcz5G+2QFfJOuaDdJHOHmyrXG2FlTo9L/zSN+mFwwBH2PrpKnybc1AtYjKWZyCEDw0HZueUmJJNGLEL69YewAxNJQEyf9dg3CgSESHTesNBkikJneViiF+DgrnAgovOQxKK73NABpfZ5LoZz0iPk9fe2VBZsYP1grC7um2oYnTuZHmhOjFmFYXxT2MTmZspt2CwL22JNi8zygJKZtnvbCOL+4xPdHUiMgi/utgQ/80NtoWhQX+oevmVJ9x03qJRLBmnHmQFgVKSA3Wg168g9RiaUaPdfKjwvyQk+VIf7iD/02K761IfOlDFQrqkMMJUTSB97MyeV9l3s2PW/XKIW94Tq/XFUm7SMScqGJdcWB9rPGGBGqvlUNyeu+0mVICfSBFstu42cB8xOHHBtBJ+Yjylpvj9+M5eMpueERE52GrDUvZSxm+mDhBwJzM0rNRNfrqERpl9+cAI9exbyjSC2cpahRa/PUzPSz3+Hn5I5uEaHgl57sG0+mK/EuEoSy6lofNhFQgd9ji8OrLgzy/e6xe+w/T3OA=
  skip_cleanup: true
  on:
    branch: master
    tags: true
