language: node_js
sudo: false
node_js:
- 5.2
- 4.2
script:
- npm run ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: kEe/1t2dhIveAEb7fBTz5PCjZwwSBQqfuxlXYAXPmOqPXX+2OyUNyki+/lyrVpmFhzKE2hGJWY5HTmhPCKRrJyqu9oH3D2yfxkm6w3pOdG3h2angHI2T9faGsvdHkGGaRVFzdn+G5g9Lbu3nbYMlR+QTP20MM1YBWTTq0HJ7BzV4e5FAyv05CoTOSbHtVq7SdAKCWn7Wz01efabQni7kAoMSOfoQLvru4yYpRB6Ype72v5R3kBW1sqciTjpEHLg/uGaUFAIsRPIva8ZZhGnG8zFLsSSeNM1FfV9obzrBMTzqlpniVXvb/sdqNZwxPwpA1foJJJ6Hj19BCA5W25vGrA8m5oucd3Vd2cEl7IdMPDRY6Dzr5O4z6YSOGUiDkQTIaiLgDKqNBYLnyh3gjLW7fu8bL36LVxJ5R7pwmvE1mXHqq0SQS9ShgBFLBNXmxEdGkBxSCglqjnDJqO8ZAbIm21ASAS1q4WElHSxF/e+S2HM0AkXcYmROWrNQLYEIS7Fw+S65QZFiEJCmh1kVWwly9yYFbiUJoN9tWGLo5wYkWtFIclCrLHBc/WD0N0nzKSL6eDluQKYGEcHmcSp07zKnrVGr6HmLad4dCuH6YteO8Z16+tIayXgfJuO90zEpC4bxT7kgbZx7LIaj64VVDsVp4J08k11LWsUMxCTJ9xIx/ho=
  skip_cleanup: true
  on:
    branch: master
    tags: true